import React from 'react';
import DashboardLayout from "@/components/online/dashboard/dashboard-layout";
import Head from "next/head";
import LessonHeader from "@/components/online/dashboard/module-lesson/lesson-header";
import LessonVideo from "@/components/online/dashboard/module-lesson/lesson-video";
import LessonDescription from "@/components/online/dashboard/module-lesson/lesson-description";
import LessonRate from "@/components/online/dashboard/module-lesson/lesson-rate";
import LessonSent from "@/components/online/dashboard/module-lesson/lesson-sent";
import {DashboardAuthGuard} from "@/components/online/dashboard/auth/dashboard-auth-guard";


const ModuleLesson = () => {
    return (
        <>
            <Head>
                <title>Online | {process.env.NEXT_PUBLIC_COMPANY_NAME}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <LessonHeader/>
            <LessonVideo/>
            <LessonDescription/>
            <LessonRate/>
            <LessonSent/>
        </>
    );
};

ModuleLesson.getLayout = page => (
    <DashboardAuthGuard>
        <DashboardLayout>
            {page}
        </DashboardLayout>
    </DashboardAuthGuard>
)

export default ModuleLesson;