import React from "react";
import OnlineLayout from "@/components/online/online-layout";
import OnlineHero from "@/components/online/online-hero";
import OnlineCourses from "@/components/online/online-courses";
import Head from "next/head";
import OnlineComments from "@/components/online/online-comments";
import ContactBanner from "@/components/global/contact-banner";
import {getOnline} from "@/api-functions/pages/get-online";

export const getStaticProps = async () => {
    const data = await getOnline()

    return {
        props: {
            onlineData: data?.results
        },
        revalidate: 60
    }
}

const OnlineHome = (props) => {
    const {onlineData} = props


    return (
        <>
            <Head>
                <title>Online | {process.env.NEXT_PUBLIC_COMPANY_NAME}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <OnlineHero/>
            <OnlineCourses courses={onlineData?.courses}/>
            <OnlineComments comments={onlineData?.comments}/>
            <ContactBanner/>
        </>
    );
};

OnlineHome.getLayout = (page) => (
    <OnlineLayout>
        {page}
    </OnlineLayout>
);
export default OnlineHome;
