import React from 'react';
import Head from "next/head";
import DashboardLayout from "@/components/online/dashboard/dashboard-layout";
import DetailScreen from "@/components/online/dashboard/course-detail/detail-screen";
import {DashboardAuthGuard} from "@/components/online/dashboard/auth/dashboard-auth-guard";

const Course = () => {
	return (
		<>
			<Head>
				<title>Online | {process.env.NEXT_PUBLIC_COMPANY_NAME}</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<DetailScreen/>
		</>
	);
};

Course.getLayout = page => (
	<DashboardAuthGuard>
		<DashboardLayout>
			{page}
		</DashboardLayout>
	</DashboardAuthGuard>
)

export default Course;