import React, {useEffect} from "react";
import MainLayout from "@/components/global/main-layout";
import Head from "next/head";
import AboutHero from "@/components/about/about-hero";
import AboutInfo from "@/components/about/about-info";
import AboutGallery from "@/components/about/about-gallery";
import ContactBanner from "@/components/global/contact-banner";
import AboutTrainings from "@/components/about/about-trainings";
import AboutTeam from "@/components/about/about-team";
import {getAbout} from "@/api-functions/pages/get-about";

export const getStaticProps = async () => {
    const data = await getAbout()

    return {
        props: {
            aboutData: data?.results
        },
        revalidate: 60
    }
}

function About(props) {
    const {aboutData} = props

    return (
        <>
            <Head>
                <title>Biz haqimizda | {process.env.NEXT_PUBLIC_COMPANY_NAME}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AboutHero/>
            <AboutInfo/>
            <AboutGallery galery={aboutData?.galery}/>
            <AboutTrainings trainings={aboutData?.training}/>
            <AboutTeam mentors={aboutData?.mentors}/>
            <ContactBanner/>
        </>
    );
}

About.getLayout = (page) => <MainLayout>{page}</MainLayout>;

export default About;
