import React from 'react';
import MainLayout from "@/components/global/main-layout";
import {Box, Container, Grid, Typography} from "@mui/material";
import Image from "next/image";
import ContactForm from "@/components/contact/contact-form";
import Head from "next/head";

function Contact(props) {
    const {
        ...other
    } = props;

    return (
        <>
            <Head>
                <title>Bog&apos;lanish | {process.env.NEXT_PUBLIC_COMPANY_NAME}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Box
                {...other}
            >
                <Box
                    sx={{
                        py: 4,
                    }}
                >
                    <Container>
                        <Box
                            sx={{
                                mb: 4,
                                maxWidth: 670
                            }}
                        >
                            <Typography variant="h2">Hoziroq ro’yxatdan o’ting!</Typography>
                            <Typography
                                variant="body1"
                                sx={{
                                    mt: 3
                                }}
                            >
                                Nimadan boshlashni, qaysi kurs sizga mos kelishini bilmayapsizmi?
                                Bizga murojaat qililng, sizga to’g’ri yo’lni ko’rsatamiz.
                            </Typography>
                        </Box>
                        <Grid
                            container
                            spacing={3}
                        >
                            <Grid
                                item
                                xs={12}
                                md={6}
                            >
                                <ContactForm/>
                            </Grid>
                            <Grid
                                item
                                xs={12}
                                md={6}
                            >
                                <Box>
                                    <Image
                                        src="/static/contact.svg"
                                        alt="contact"
                                        width={500}
                                        height={500}
                                        style={{
                                            width: "100%"
                                        }}
                                    />
                                </Box>
                            </Grid>
                        </Grid>
                    </Container>
                </Box>
            </Box>
        </>
    );
}

Contact.getLayout = page => (
    <MainLayout>
        {page}
    </MainLayout>
)

export default Contact;