import React from 'react';
import Head from "next/head";
import DashboardLayout from "@/components/online/dashboard/dashboard-layout";
import {DashboardAuthGuard} from "@/components/online/dashboard/auth/dashboard-auth-guard";
import {Box, Container, Typography} from "@mui/material";
import {useAuth} from "@/hooks/use-auth";
import CourseList from "@/components/online/dashboard/course/course-list";
import DashboardCoursesListSkeleton from "@/components/online/dashboard/skeletons/dashboard-courses-list-skeleton";
import {useQuery} from "react-query";
import {getUserCourseList} from "@/api-functions/user/get-user-course-list";

const Index = () => {
	const {user} = useAuth();
	const {
		data,
		isLoading
	} = useQuery({
		queryKey: ["user", user?.id, "courses"],
		queryFn: () => getUserCourseList({
			token: user?.access_token,
			userId: user?.id
		})
	})

	return (
		<>
			<Head>
				<title>Online | {process.env.NEXT_PUBLIC_COMPANY_NAME}</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<Box
				component="main"
				sx={{py: 8}}
			>
				{isLoading ? <DashboardCoursesListSkeleton/> : (
					<Box>
						<Container>
							<Box
								sx={{mb: 8}}
							>
								<Typography variant='h2'>
									Salom, {user?.first_name}!
								</Typography>
								<Typography sx={{fontWeight: 500}}>
									Yangi bilimlar olish uchun qulay fursat.
								</Typography>
							</Box>
							<CourseList courses={data?.results}/>
						</Container>
					</Box>
				)}

			</Box>
		</>
	);
};

Index.getLayout = page => (
	<DashboardAuthGuard>
		<DashboardLayout>
			{page}
		</DashboardLayout>
	</DashboardAuthGuard>
)
export default Index;